name: ItemSolution
version: 1.0 # the plugin's version
author: Leon
main: top.leonx.itemsolution.ItemSolution
api-version: 1.13
description: Item Solution plugin
commands:
  itemsolution:
    aliases:
      - itemso
    description: "Clear the items in world"
    usage: /<command> [reload|clear]
    permission: itemsolution.command